[role="xpack"]
[testenv="basic"]
[[info-api]]
== 信息 API

信息 API 提供了 {xpack} 已安装功能的概要信息。

[float]
=== 请求

`GET /_xpack`

[float]
=== 说明

通过信息 API 可获取以下信息：

* 构建（Build）信息 - 包括内部版本号和时间戳。
* 许可证（License）信息 - 当前安装的许可证的基本信息。
* 功能（Features）信息 - 当前许可证下已启用和可用的功能。

[float]
=== 路径参数

`categories`::
  (list) 要包含在响应中的的信息类别列表，以逗号分隔。例如：`build,license,features`。

`human`::
  (boolean) 定义响应中是否包含附加的人类可读的信息，它将会添加描述项和标记行。该配置项的默认值为 `true`。

//=== Query Parameters

//=== Authorization

[float]
=== 示例

下面是信息 API 的查询示例：

[source,js]
------------------------------------------------------------
GET /_xpack
------------------------------------------------------------
// CONSOLE

示例响应：
[source,js]
------------------------------------------------------------
{
   "build" : {
      "hash" : "2798b1a3ce779b3611bb53a0082d4d741e4d3168",
      "date" : "2015-04-07T13:34:42Z"
   },
   "license" : {
      "uid" : "893361dc-9749-4997-93cb-xxx",
      "type" : "trial",
      "mode" : "trial",
      "status" : "active",
      "expiry_date_in_millis" : 1542665112332
   },
   "features" : {
      "graph" : {
         "description" : "Graph Data Exploration for the Elastic Stack",
         "available" : true,
         "enabled" : true
      },
      "logstash" : {
         "description" : "Logstash management component for X-Pack",
         "available" : true,
         "enabled" : true
      },
      "ml" : {
         "description" : "Machine Learning for the Elastic Stack",
         "available" : true,
         "enabled" : true,
         "native_code_info" : {
           "version" : "6.5.0-SNAPSHOT",
           "build_hash" : "3d394c6afe2fc5"
        }
      },
      "monitoring" : {
         "description" : "Monitoring for the Elastic Stack",
         "available" : true,
         "enabled" : true
      },
      "rollup": {
        "description": "Time series pre-aggregation and rollup",
         "available": true,
         "enabled": true
      },
      "security" : {
         "description" : "Security for the Elastic Stack",
         "available" : true,
         "enabled" : false
      },
      "watcher" : {
         "description" : "Alerting, Notification and Automation for the Elastic Stack",
         "available" : true,
         "enabled" : true
      }
   },
   "tagline" : "You know, for X"
}
------------------------------------------------------------
// TESTRESPONSE[s/"hash" : "2798b1a3ce779b3611bb53a0082d4d741e4d3168",/"hash" : "$body.build.hash",/]
// TESTRESPONSE[s/"date" : "2015-04-07T13:34:42Z"/"date" : "$body.build.date"/]
// TESTRESPONSE[s/"uid" : "893361dc-9749-4997-93cb-xxx",/"uid": "$body.license.uid",/]
// TESTRESPONSE[s/"expiry_date_in_millis" : 1542665112332/"expiry_date_in_millis" : "$body.license.expiry_date_in_millis"/]
// TESTRESPONSE[s/"version" : "6.5.0-SNAPSHOT",/"version": "$body.features.ml.native_code_info.version",/]
// TESTRESPONSE[s/"build_hash" : "3d394c6afe2fc5"/"build_hash": "$body.features.ml.native_code_info.build_hash"/]
// So much s/// but at least we test that the layout is close to matching....

下面的示例仅返回构建和功能信息：

[source,js]
------------------------------------------------------------
GET /_xpack?categories=build,features
------------------------------------------------------------
// CONSOLE

下面的示例移除了响应中的描述信息：

[source,js]
------------------------------------------------------------
GET /_xpack?human=false
------------------------------------------------------------
// CONSOLE
